#Defines or set active application profile: live or development
spring.profiles.active: development

---

spring:
  profiles: development
  application.name: DotLogAnalyzer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/req_limit?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.show_sql: false
    properties.hibernate.use_sql_comments: true
    properties.hibernate.format_sql: true
    properties.hibernate.type: trace
    hibernate.ddl-auto: update
  servlet:
    multipart.enabled: true
    multipart.file-size-threshold: 2KB
    multipart.max-file-size: 200MB
    multipart.max-request-size: 215MB
  batch:
    initialize-schema: ALWAYS
    job.enabled: false

  http.multipart.max-file-size: 50MB

logging:
  file: logs/application.log
  file.max-size: 200MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.netflix.discovery.DiscoveryClient: INFO
    com.drone.manager: INFO
    org.springframework.security: INFO

server.port: 8084
duration: hourly

---

spring:
  profiles: live
  application.name: DotLogAnalyzer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/req_limit?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.show_sql: false
    properties.hibernate.use_sql_comments: true
    properties.hibernate.format_sql: true
    properties.hibernate.type: trace
    hibernate.ddl-auto: update
  servlet:
    multipart.enabled: true
    multipart.file-size-threshold: 2KB
    multipart.max-file-size: 200MB
    multipart.max-request-size: 215MB

  http.multipart.max-file-size: 10MB

logging:
  file: logs/application.log
  file.max-size: 200MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.netflix.discovery.DiscoveryClient: INFO
    com.drone.manager: INFO
    org.springframework.security: INFO

server.port: 8084
duration: hourly